routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Habbo WebPages Routes
|--------------------------------------------------------------------------
|
| Here are registered all HabboWEB Pages Routes
| Those Routes are special, like News, Advertisement, and others.
|
*/

// Main HabboPAGES Request is Forbidden
$router->get('habbo-web-pages/', function () {
    return response('Unauthorized.', 401);
});

// Request a Specific View of HabboWEB Pages
$router->get('habbo-web-pages/production/{category}/{view}', 'PageController@show');

app/Models/GroupMember.php
<?php

namespace App\Models;

/**
 * Class GroupMember.
 */
class GroupMember extends ChocolateyModel
{
    /**
     * Disable Timestamps.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'guilds_members';

    /**
     * Primary Key of the Table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['id', 'member_since', 'guild_id', 'level_id', 'user_id'];

    /**
     * The Appender(s) of the Model.
     *
     * @var array
     */
    protected $appends = ['guild'];

    /**
     * Get User Group by Member Group Id.
     *
     * @return UserGroup
     */
    public function getGuildAttribute(): UserGroup
    {
        return UserGroup::find($this->attributes['guild_id']);
    }

    /**
     * Get Description Attribute.
     *
     * @TODO: Get Real Badge Description
     *
     * @return string
     */
    public function getDescriptionAttribute(): string
    {
        return "Badge {$this->attributes['badge_code']}";
    }
}

resources/views/habbo-web-news/articles-category.blade.php
<!-- View stored in resources/views/ArticlesCategory.php -->
<section>
    <header class="news-category__header">
        <span translate="NEWS_SHOW_MORE"></span>
        <nav class="news-category__navigation">
            <ul class="news-category__list">
                @foreach ($categories as $articleCategory)
                    <li class="news-category__item">
                        @if ($articleCategory->name == $category->name)
                            <a href="/community/category/{{$articleCategory->name}}"
                               translate="{{$articleCategory->translate}}"
                               class="news-category__link--active news-category__link">
                            </a>
                        @else
                            <a href="/community/category/{{$articleCategory->name}}"
                               translate="{{$articleCategory->translate}}"
                               class="news-category__link">
                            </a>
                        @endif
                    </li>
                @endforeach
            </ul>
        </nav>
    </header>
    @foreach ($articles as $articleContent)
        <article class="news-header">
            @if($articleContent->roomId != 0)
                <a href="/hotel?room={{$articleContent->roomId}}"
                   class="news-header__link news-header__banner">
                    <figure class="news-header__viewport">
                        <img src="{{$articleContent->thumbnailUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--thumbnail">
                        <img src="{{$articleContent->imageUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--featured">
                    </figure>
                </a>
                <a href="/hotel?room={{$articleContent->roomId}}" class="news-header__link news-header__wrapper">
                    <h2 class="news-header__title">{{$articleContent->title}}</h2>
                </a>
            @else
                <a href="/community/article/{{$articleContent->id}}/content"
                   class="news-header__link news-header__banner">
                    <figure class="news-header__viewport">
                        <img src="{{$articleContent->thumbnailUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--thumbnail">
                        <img src="{{$articleContent->imageUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--featured">
                    </figure>
                </a>
                <a href="/community/article/{{$articleContent->id}}/content"
                   class="news-header__link news-header__wrapper">
                    <h2 class="news-header__title">{{$articleContent->title}}</h2>
                </a>
            @endif
            <aside class="news-header__wrapper news-header__info">
                <time class="news-header__date">
                    {{date('M j, Y' , strtotime($articleContent->createdAt))}}
                </time>
                <ul class="news-header__categories">
                    @foreach ($articleContent->categories as $articleCategory)
                        <li class="news-header__category">
                            <a href="/community/category/{{$articleCategory->name}}"
                               class="news-header__category__link"
                               translate="{{$articleCategory->translate}}"></a>
                        </li>
                    @endforeach
                </ul>
            </aside>
            <p class="news-header__wrapper news-header__summary">{{$articleContent->description}}</p>
        </article>
    @endforeach

    <footer>
        <nav>
            <ul>
                @if($page > 1)
                    <li>
                        <a href="/community/category/{{$category->name}}/{{$page - 1}}" translate="NEWS_PREVIOUS"
                           class="news-category__previous"></a>
                    </li>
                @endif
                @if($articles->count() == 10)
                    <li>
                        <a href="/community/category/{{$category->name}}/{{$page + 1}}" translate="NEWS_NEXT"
                           class="news-category__next"></a>
                    </li>
                @endif
            </ul>
        </nav>
    </footer>
</section>

resources/views/habbo-web-news/articles-front.blade.php
<section>
    @foreach ($set as $articleContent)
        <article class="news-header news-header--column">
            @if($articleContent->roomId != 0)
                <a href="/hotel?room={{$articleContent->roomId}}"
                   class="news-header__link news-header__banner">
                    <figure class="news-header__viewport">
                        <img src="{{$articleContent->thumbnailUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--thumbnail">
                        <img src="{{$articleContent->imageUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--featured">
                    </figure>
                </a>
                <a href="/hotel?room={{$articleContent->roomId}}" class="news-header__link news-header__wrapper">
                    <h2 class="news-header__title">{{$articleContent->title}}</h2>
                </a>
            @else
                <a href="/community/article/{{$articleContent->id}}/content"
                   class="news-header__link news-header__banner">
                    <figure class="news-header__viewport">
                        <img src="{{$articleContent->thumbnailUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--thumbnail">
                        <img src="{{$articleContent->imageUrl}}"
                             alt="{{$articleContent->title}}" class="news-header__image news-header__image--featured">
                    </figure>
                </a>
                <a href="/community/article/{{$articleContent->id}}/content" class="news-header__link news-header__wrapper">
                    <h2 class="news-header__title">{{$articleContent->title}}</h2>
                </a>
            @endif
            <aside class="news-header__wrapper news-header__info">
                <time class="news-header__date">
                    {{date('M j, Y' , strtotime($articleContent->createdAt))}}
                </time>
                <ul class="news-header__categories">
                    @foreach ($articleContent->categories as $articleCategory)
                        <li class="news-header__category">
                            <a href="/community/category/{{$articleCategory->name}}"
                               class="news-header__category__link"
                               translate="{{$articleCategory->translate}}"></a>
                        </li>
                    @endforeach
                </ul>
            </aside>
            <p class="news-header__wrapper news-header__summary">{{$articleContent->description}}</p>
        </article>
    @endforeach
</section>

resources/views/habbo-web-news/articles-view.blade.php
<article>
    <header class="news-header news-header--single">
        <div class="news-header__banner">
            <figure class="news-header__viewport">
                <img src="{{$article->imageUrl}}"
                     alt="{{$article->title}}"
                     class="news-header__image news-header__image--featured">
            </figure>
        </div>
        <habbo-social-share type="news"></habbo-social-share>
        <h1 class="news-header__wrapper news-header__title">{{$article->title}}</h1>
        <aside class="news-header__wrapper news-header__info">
            <time class="news-header__date">
                {{date('M j, Y' , strtotime($article->createdAt))}}
            </time>
            <ul class="news-header__categories">
                @foreach ($article->categories as $articleCategory)
                    <li class="news-header__category">
                        <a href="/community/category/{{$articleCategory->name}}"
                           class="news-header__category__link"
                           translate="{{$articleCategory->translate}}"></a>
                    </li>
                @endforeach
            </ul>
        </aside>
        <p class="news-header__wrapper news-header__summary">
            {{$article->description}}
        </p>
    </header>
    <div class="news-article">
        {!! $article->content !!}
    </div>

    <div class="news-footer">
        <aside class="news-box">
            <h4 translate="NEWS_RELATED"></h4>
            <ul>
                @foreach ($related as $relatedContent)
                    <li class="news-box__item">
                        <a href="/community/article/{{$relatedContent->id}}/content" class="news-box__link">
                            {{$relatedContent->title}}
                        </a>
                        <time class="news-box__date">
                            ({{date('M j, Y' , strtotime($relatedContent->createdAt))}})
                        </time>
                    </li>
                @endforeach
            </ul>
        </aside>
        <aside class="news-box">
            <h4 translate="NEWS_NEWEST"></h4>
            <ul>
                @foreach ($latest as $relatedContent)
                    <li class="news-box__item">
                        <a href="/community/article/{{$relatedContent->id}}/content" class="news-box__link">
                            {{$relatedContent->title}}
                        </a>
                        <time class="news-box__date">
                            ({{date('M j, Y' , strtotime($relatedContent->createdAt))}})
                        </time>
                    </li>
                @endforeach
            </ul>
        </aside>
    </div>
</article>